#spring.application.name=digital-wallet
server:
  port: 8080
  servlet:
    context-path: /wallet

spring:
  datasource:
    url: ${DBMS_URL}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      group-id: digital-wallet-kafka
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: TRACE


jwt:
  signerKey: ${JWT_SIGNERKEY}
  token :
    access-time: 7
    refresh-time: 7

rate-limit:
  transfer:
    max-requests: 10
    window-seconds: 30

  top-up:
    max-requests: 10
    window-seconds: 60

  login:
    max-requests: 100
    window-seconds: 60


